import { cardPoint, handTotal, settleRound } from "./baccarat-rules.mjs";
import { renderCardFace } from "./card-renderer.mjs";
import { inferRankCandidates } from "./candidate-geometry.mjs";
import { canGrabSqueezeBoundary, clipForDirection, detectSqueezeDirection, progressFromBoundary } from "./squeeze-geometry.mjs";

const SAVE_KEY = "velvet-table-save-v2";
const STARTING_CHIPS = 1000;
const SUITS = [{ symbol: "♠", color: "black" }, { symbol: "♥", color: "red" }, { symbol: "♦", color: "red" }, { symbol: "♣", color: "black" }];
const RANKS = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const PHASE_LABELS = { betting: "BETTING", dealing: "DEALING", revealing: "REVEALING", third: "DRAWING", settled: "SETTLED" };
const SQUEEZE_COMPLETE_THRESHOLD = 95;

let state = loadState();
let game = freshGame();
let squeezeMode = "auto";
let pointerSession = null;
let suppressClick = false;
let lastSqueezeTrigger = null;
let squeezeCuePlayed = false;
const squeezeView = { isSqueezeViewOpen: false, activeSqueezeCardId: null, squeezeViewPhase: "closing", squeezeDirection: null, horizontalProgress: 0, verticalProgress: 0, cornerProgress: 0, revealRegions: {}, totalRevealedArea: 0, isPointerActive: false, activePointerId: null, isAnimating: false, cardRect: null };

function loadState() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY)); return saved ? { balance: saved.balance ?? STARTING_CHIPS, history: saved.history ?? [], nextRound: saved.nextRound ?? (saved.history?.length ?? 0) + 1 } : { balance: STARTING_CHIPS, history: [], nextRound: 1 }; } catch { return { balance: STARTING_CHIPS, history: [], nextRound: 1 }; } }
function saveState() { localStorage.setItem(SAVE_KEY, JSON.stringify(state)); }
function nextRoundNumber() { const round = state.nextRound ?? 1; state.nextRound = round + 1; return round; }
function freshGame() { return { phase: "betting", round: nextRoundNumber(), playerHand: [], bankerHand: [], currentTurn: null, result: null, bets: { target: null, amount: 0, sideBets: [] }, payout: 0, isAnimating: false, settled: false, thirdChecked: false, autoReveal: false }; }
function formatChips(value) { return value.toLocaleString("ja-JP"); }
function wait(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
function squeezeAnimationDuration() { return window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ? 0 : 380; }
function triggerSqueezeCue() { if (squeezeCuePlayed) return; squeezeCuePlayed = true; try { navigator.vibrate?.(8); } catch {} }
function drawCard(owner, order, isThirdCard = false) { const suit = SUITS[Math.floor(Math.random() * SUITS.length)]; const rank = RANKS[Math.floor(Math.random() * RANKS.length)]; return { id: `${owner}-${order}-${Date.now()}-${Math.random().toString(16).slice(2)}`, rank, suit: suit.symbol, color: suit.color, owner, order, isDealt: false, revealState: "hidden", squeezeProgress: 0, horizontalProgress: 0, verticalProgress: 0, cornerProgress: 0, activeDirection: null, squeezeDirection: "left", revealRegions: {}, orientation: "portrait", isThirdCard }; }
function getHand(owner) { return owner === "PLAYER" ? game.playerHand : game.bankerHand; }
function getHiddenCards(owner) { return getHand(owner).filter(card => card.isDealt && card.revealState !== "revealed"); }
function getVisibleCards(owner) { return getHand(owner).filter(card => card.isDealt && card.revealState === "revealed"); }
function allDealtCardsRevealed() { return [...game.playerHand, ...game.bankerHand].filter(card => card.isDealt).every(card => card.revealState === "revealed"); }
function squeezeFacesMarkup(card) { return Object.entries(card.revealRegions).filter(([, progress]) => progress > 0).map(([direction, progress]) => `<span class="squeeze-face squeeze-region-${direction}" style="clip-path:${clipForDirection(direction, progress)}"><span class="squeeze-boundary">${renderCardFace({ ...card, faceUp: false, squeezeProgress: progress })}</span></span>`).join(""); }
function cardMarkup(card) {
  if (!card.isDealt) return "";
  if (card.revealState === "squeezing") return `<button class="card card-back reveal-card is-squeezing ${card.orientation === "landscape" ? "is-landscape" : ""}" data-card-id="${card.id}" type="button" aria-label="絞り中の裏向きカード。クリックで絞り専用ビューを開く">${squeezeFacesMarkup(card)}</button>`;
  if (card.revealState !== "revealed") return `<button class="card card-back reveal-card" data-card-id="${card.id}" type="button" aria-label="裏向きのカード。タップで公開、ドラッグで絞る">?</button>`;
  return `<button class="card card-face ${card.orientation === "landscape" ? "is-landscape" : ""}" data-card-id="${card.id}" type="button" aria-label="公開済みカード">${renderCardFace({ ...card, faceUp: true })}</button>`;
}
function updateSqueezingCard(card) {
  const element = document.querySelector(`.reveal-card[data-card-id="${card.id}"]`);
  if (!element) return;
  element.className = `card card-back reveal-card is-squeezing ${card.orientation === "landscape" ? "is-landscape" : ""}`;
  element.innerHTML = squeezeFacesMarkup(card);
}
function syncSqueezeCandidates(card) { const direction = card.activeDirection; const progress = card.revealRegions[direction] ?? 0; const modalCard = document.querySelector("#squeezeModalCard"); const panel = document.querySelector("#squeezeCandidates"); const value = document.querySelector("#squeezeCandidateValues"); const status = document.querySelector("#squeezeCandidateStatus"); if (!modalCard || !panel || !value || !status) return; const pips = [...modalCard.querySelectorAll(`.squeeze-region-${direction} use`)].filter(node => Number(node.getAttribute("width")) >= 19).map(node => ({ x: Number(node.getAttribute("x")) + Number(node.getAttribute("width")) / 2, y: Number(node.getAttribute("y")) + Number(node.getAttribute("height")) / 2 })); const candidates = inferRankCandidates(pips, direction, progress); panel.hidden = false; panel.classList.toggle("is-confirmed", candidates.length === 1); panel.classList.toggle("is-likely", candidates.length === 2); value.textContent = candidates.length ? candidates.map(rank => `[${rank}]`).join(" ") : "候補なし"; status.textContent = candidates.length === 1 ? `○で確定: ${candidates[0]}` : candidates.length === 2 ? "可能性が濃厚 · もう一段階で確定する可能性があります" : candidates.length ? `${candidates.length}候補 · もう一段階で確定する可能性があります` : "候補を判定中"; }
function syncSqueezeView(card) { const modal = document.querySelector("#squeezeModal"); const modalCard = document.querySelector("#squeezeModalCard"); if (!card || !modal || !modalCard || squeezeView.activeSqueezeCardId !== card.id) return; document.querySelector("#squeezeModalTitle").textContent = `${card.owner} · ${card.order}枚目`; document.querySelector("#squeezeProgressLabel").textContent = `${Math.round(squeezeView.totalRevealedArea)}%`; modalCard.innerHTML = card.revealState === "revealed" ? renderCardFace({ ...card, faceUp: true }) : squeezeFacesMarkup(card); document.querySelectorAll("#squeezeDirectionPicker button").forEach(button => button.classList.toggle("is-selected", button.dataset.squeezeDirection === card.activeDirection)); ["left", "right", "bottom"].forEach(direction => modal.classList.toggle(`squeeze-direction-${direction}`, card.activeDirection === direction)); syncSqueezeCandidates(card); modal.classList.toggle("is-complete", card.revealState === "revealed"); }
function renderHand(owner) { const cards = getHand(owner); const id = owner === "PLAYER" ? "playerCards" : "bankerCards"; document.querySelector(`#${id}`).innerHTML = cards.filter(card => card.isDealt).map(cardMarkup).join(""); const visible = getVisibleCards(owner); const total = handTotal(visible); const fullyOpen = cards.length > 0 && cards.filter(card => card.isDealt).every(card => card.revealState === "revealed"); const score = document.querySelector(owner === "PLAYER" ? "#playerTotal" : "#bankerTotal"); score.textContent = fullyOpen ? total : visible.length ? `${total} · 暫定` : "?"; }
function renderHistory() { const list = document.querySelector("#historyList"); if (!state.history.length) { list.innerHTML = `<p class="empty-state">まだラウンド履歴がありません。</p>`; return; } list.innerHTML = state.history.map(item => `<div class="history-row"><span class="history-round">#${String(item.round).padStart(2, "0")}</span><span class="history-bet">${item.target.toUpperCase()} · ${formatChips(item.bet)}</span><strong class="history-winner">${item.winner.toUpperCase()} ${item.playerTotal} - ${item.bankerTotal}</strong><span class="history-result ${item.won ? "is-win" : "is-lose"}">${item.won ? `+${formatChips(item.payout)}` : "LOSE"}</span></div>`).join(""); }
function render() {
  document.querySelector("#balanceValue").textContent = formatChips(state.balance); document.querySelector("#roundLabel").textContent = `ROUND ${String(game.round).padStart(2, "0")}`; document.querySelector("#phaseLabel").textContent = PHASE_LABELS[game.phase];
  renderHand("PLAYER"); renderHand("BANKER"); renderHistory();
  const betReady = game.bets.target && game.bets.amount > 0 && totalStake() <= state.balance;
  document.querySelector("#dealButton").disabled = game.phase !== "betting" || !betReady;
  document.querySelector("#revealAllButton").disabled = !["revealing", "third"].includes(game.phase) || game.isAnimating;
  document.querySelector("#newRoundButton").disabled = game.phase !== "settled";
  document.querySelectorAll(".reveal-side-button, .squeeze-side-button, .reveal-all-side-button").forEach(button => { const hand = getHand(button.dataset.owner); button.disabled = !["revealing", "third"].includes(game.phase) || game.isAnimating || !getHiddenCards(button.dataset.owner).length; });
  document.querySelectorAll(".target-button, .chip-button, .side-bet-button").forEach(button => { button.disabled = game.phase !== "betting"; });
  document.querySelector("#clearBet").disabled = game.phase !== "betting";
  if (squeezeView.isSqueezeViewOpen) syncSqueezeView(findCard(squeezeView.activeSqueezeCardId));
}
function totalStake() { return game.bets.amount * (1 + game.bets.sideBets.length); }
function setMessage(message) { document.querySelector("#tableMessage").textContent = message; }
function setCardsDealt(cards) { cards.forEach(card => { card.isDealt = true; }); }
async function startGame() {
  if (game.phase !== "betting" || totalStake() > state.balance || !game.bets.target) return;
  state.balance -= totalStake(); game.phase = "dealing"; game.isAnimating = true; setMessage("カードを配っています…"); render();
  game.playerHand = [drawCard("PLAYER", 1), drawCard("PLAYER", 2)]; game.bankerHand = [drawCard("BANKER", 1), drawCard("BANKER", 2)];
  const order = [game.playerHand[0], game.bankerHand[0], game.playerHand[1], game.bankerHand[1]];
  for (const card of order) { card.isDealt = true; render(); await wait(360); }
  game.isAnimating = false; game.phase = "revealing"; game.currentTurn = "PLAYER"; setMessage("カードをタップして、PLAYERまたはBANKERを開いてください"); render();
}
function findCard(id) { return [...game.playerHand, ...game.bankerHand].find(card => card.id === id); }
function revealCard(id, internal = false) { const card = findCard(id); if (!card || !card.isDealt || card.revealState === "revealed" || (game.isAnimating && !internal)) return false; card.revealState = "revealed"; card.squeezeProgress = 100; card.horizontalProgress = 100; card.verticalProgress = 100; card.cornerProgress = 100; card.orientation = "portrait"; render(); return true; }
async function revealSide(owner) { if (squeezeView.isSqueezeViewOpen || !["revealing", "third"].includes(game.phase) || game.isAnimating) return; const hidden = getHiddenCards(owner); if (!hidden.length) return; game.isAnimating = true; for (const card of hidden) { revealCard(card.id, true); await wait(420); } game.isAnimating = false; await afterReveal(); render(); }
async function revealAll() { if (squeezeView.isSqueezeViewOpen || !["revealing", "third"].includes(game.phase) || game.isAnimating) return; game.autoReveal = true; game.isAnimating = true; let safety = 0; while (safety++ < 12) { const hidden = [...game.playerHand, ...game.bankerHand].filter(card => card.isDealt && card.revealState !== "revealed"); if (!hidden.length) break; const side = hidden[0].owner; const next = hidden.find(card => card.owner === side) || hidden[0]; revealCard(next.id, true); await wait(430); if (allDealtCardsRevealed() && !game.thirdChecked) { game.isAnimating = false; await afterReveal(); game.isAnimating = true; } } game.isAnimating = false; await afterReveal(); game.autoReveal = false; render(); }
async function afterReveal() { if (!allDealtCardsRevealed()) { render(); return; } if (game.thirdChecked) { settleIfReady(); return; } game.thirdChecked = true; const playerTotal = handTotal(game.playerHand); const bankerTotal = handTotal(game.bankerHand); const natural = playerTotal >= 8 || bankerTotal >= 8; let playerThirdValue = null; if (!natural && playerTotal <= 5) { game.playerHand.push(drawCard("PLAYER", 3, true)); playerThirdValue = cardPoint(game.playerHand[2]); } if (!natural && shouldBankerDraw(bankerTotal, playerThirdValue)) game.bankerHand.push(drawCard("BANKER", 3, true)); const added = [...game.playerHand, ...game.bankerHand].filter(card => !card.isDealt); if (added.length) { game.phase = "third"; added.forEach(card => { card.isDealt = true; }); setMessage(added.map(card => `${card.owner}に3枚目が配られます`).join(" / ")); render(); return; } setMessage(natural ? "ナチュラルのため追加カードはありません。すべて公開されました。" : "追加カードはありません。結果を確定します。"); settleIfReady(); }
function shouldBankerDraw(bankerTotal, playerThirdValue) { if (playerThirdValue === null) return bankerTotal <= 5; if (bankerTotal <= 2) return true; if (bankerTotal === 3) return playerThirdValue !== 8; if (bankerTotal === 4) return playerThirdValue >= 2 && playerThirdValue <= 7; if (bankerTotal === 5) return playerThirdValue >= 4 && playerThirdValue <= 7; if (bankerTotal === 6) return playerThirdValue === 6 || playerThirdValue === 7; return false; }
function settleIfReady() {
  if (game.settled || !game.thirdChecked || !allDealtCardsRevealed()) return;
  const settlement = settleRound({ mainTarget: game.bets.target, stake: game.bets.amount, selectedSideBets: game.bets.sideBets, playerHand: game.playerHand, bankerHand: game.bankerHand });
  const won = settlement.bets.some(bet => bet.won);
  game.result = settlement; game.payout = settlement.totalPayout; game.settled = true; game.phase = "settled";
  state.balance += settlement.totalPayout; state.history.unshift({ round: game.round, target: game.bets.target, bet: game.bets.amount, winner: settlement.winner, playerTotal: settlement.playerTotal, bankerTotal: settlement.bankerTotal, won, payout: settlement.totalPayout }); state.history = state.history.slice(0, 8); saveState();
  document.querySelector("#resultLabel").textContent = settlement.winner.toUpperCase(); document.querySelector(".table-card").classList.toggle("is-win", won); document.querySelector("#resultDetails").hidden = false;
  document.querySelector("#resultDetails").innerHTML = `<strong>最終得点 ${settlement.playerTotal} - ${settlement.bankerTotal}</strong><br>${settlement.bets.map(bet => `${bet.label} · 掛け金 ${formatChips(bet.stake)} · ${bet.won ? `${bet.multiplier} TO 1 · 払戻 ${formatChips(bet.returnAmount)}` : "はずれ · 払戻 0"}`).join("<br>")}<br>合計払戻：<strong>${formatChips(settlement.totalPayout)} チップ</strong><br>純利益：${settlement.netProfit >= 0 ? "+" : ""}${formatChips(settlement.netProfit)} チップ`;
  document.querySelector("#newRoundButton").hidden = false;
  setMessage(settlement.totalPayout ? `結果確定 · 払戻 +${formatChips(settlement.totalPayout)} チップ` : `結果確定 · ${settlement.winner.toUpperCase()}の勝利`); render();
}
function openSqueezeView(card, direction = null, trigger = null) { if (!card || card.revealState === "revealed" || squeezeView.isSqueezeViewOpen || game.isAnimating || !["revealing", "third"].includes(game.phase)) return; squeezeCuePlayed = false; lastSqueezeTrigger = trigger ?? document.querySelector(`.reveal-card[data-card-id="${card.id}"]`); squeezeView.isSqueezeViewOpen = true; squeezeView.activeSqueezeCardId = card.id; squeezeView.squeezeViewPhase = "opening"; squeezeView.squeezeDirection = direction; squeezeView.isAnimating = true; card.activeDirection = direction; card.squeezeDirection = direction ?? "auto"; card.revealState = card.revealState === "hidden" ? "squeezing" : card.revealState; squeezeView.revealRegions = card.revealRegions; squeezeView.totalRevealedArea = Math.min(100, Object.values(card.revealRegions).reduce((sum, progress) => sum + progress * .75, 0)); document.body.classList.add("is-squeeze-modal-open"); const modal = document.querySelector("#squeezeModal"); const modalCard = document.querySelector("#squeezeModalCard"); modal.hidden = false; modal.classList.remove("is-ready", "is-complete"); syncSqueezeView(card); const source = lastSqueezeTrigger?.getBoundingClientRect(); requestAnimationFrame(() => { const target = modalCard.getBoundingClientRect(); const sourceX = source ? source.left + source.width / 2 - (target.left + target.width / 2) : 0; const sourceY = source ? source.top + source.height / 2 - (target.top + target.height / 2) : 0; const sourceScale = source ? Math.min(source.width / target.width, source.height / target.height) : .2; modalCard.style.setProperty("--from-x", `${sourceX}px`); modalCard.style.setProperty("--from-y", `${sourceY}px`); modalCard.style.setProperty("--from-scale", sourceScale); modalCard.classList.add("is-opening"); }); window.setTimeout(() => { if (!squeezeView.isSqueezeViewOpen) return; squeezeView.squeezeViewPhase = "ready"; squeezeView.isAnimating = false; modal.classList.add("is-ready"); modalCard.focus({ preventScroll: true }); }, squeezeAnimationDuration()); render(); }
function closeSqueezeView() { if (!squeezeView.isSqueezeViewOpen || squeezeView.squeezeViewPhase === "closing") return; if (pointerSession) endPointer(); squeezeView.squeezeViewPhase = "closing"; squeezeView.isAnimating = true; const modal = document.querySelector("#squeezeModal"); const modalCard = document.querySelector("#squeezeModalCard"); modal.classList.remove("is-ready"); modalCard.classList.add("is-closing"); window.setTimeout(() => { modal.hidden = true; modalCard.classList.remove("is-opening", "is-closing"); document.body.classList.remove("is-squeeze-modal-open"); squeezeView.isSqueezeViewOpen = false; squeezeView.activeSqueezeCardId = null; squeezeView.squeezeViewPhase = "closing"; squeezeView.isAnimating = false; lastSqueezeTrigger?.focus?.({ preventScroll: true }); lastSqueezeTrigger = null; render(); }, squeezeAnimationDuration() || 1); }
function completeSqueezeView() { const card = findCard(squeezeView.activeSqueezeCardId); if (!card || card.revealState === "revealed" || squeezeView.squeezeViewPhase === "revealing") return; if (pointerSession) endPointer(); squeezeView.squeezeViewPhase = "revealing"; squeezeView.isAnimating = true; revealCard(card.id, true); document.querySelector("#squeezeModal").classList.add("is-complete"); window.setTimeout(() => { afterReveal(); closeSqueezeView(); }, 420); }
function setSqueezeProgress(card, direction, progress) { if (!card || card.revealState === "revealed" || !squeezeView.isSqueezeViewOpen || squeezeView.squeezeViewPhase === "opening" || squeezeView.squeezeViewPhase === "closing") return; const next = Math.max(card.revealRegions[direction] ?? 0, Math.min(100, progress)); card.revealState = "squeezing"; card.activeDirection = direction; card.squeezeDirection = direction; card.revealRegions[direction] = next; card.squeezeProgress = Math.max(...Object.values(card.revealRegions), 0); if (["left", "right"].includes(direction)) card.horizontalProgress = Math.max(card.horizontalProgress, next); else if (["top", "bottom"].includes(direction)) card.verticalProgress = Math.max(card.verticalProgress, next); else card.cornerProgress = Math.max(card.cornerProgress, next); card.orientation = "portrait"; squeezeView.revealRegions = card.revealRegions; squeezeView.totalRevealedArea = Math.min(100, Object.values(card.revealRegions).reduce((sum, value) => sum + value * .75, 0)); squeezeView.squeezeViewPhase = "squeezing"; if (next >= 15) triggerSqueezeCue(); syncSqueezeView(card); if (next >= SQUEEZE_COMPLETE_THRESHOLD) completeSqueezeView(); else render(); }
function restoreSqueezeDirection(card) { if (!card || card.activeDirection || !card.revealRegions) return; const saved = Object.entries(card.revealRegions).filter(([, progress]) => progress > 0).sort(([, first], [, second]) => second - first)[0]; if (saved) { card.activeDirection = saved[0]; card.squeezeDirection = saved[0]; } }
function isValidSqueezeStart(direction, x, y, width, height, progress) { const card = findCard(squeezeView.activeSqueezeCardId); const savedProgress = progress ?? card?.revealRegions[direction] ?? 0; return canGrabSqueezeBoundary(direction, { x: x / width, y: y / height }, savedProgress); }
function resetForNewRound() { if (game.phase !== "settled" || game.isAnimating) return; game = freshGame(); saveState(); document.querySelector("#betValue").textContent = "0"; document.querySelectorAll(".target-button, .side-bet-button").forEach(button => button.classList.remove("is-selected")); document.querySelector("#resultLabel").textContent = "BET TO DEAL"; document.querySelector("#resultDetails").hidden = true; document.querySelector("#resultDetails").innerHTML = ""; document.querySelector("#newRoundButton").hidden = true; document.querySelector("#tableMessage").textContent = "ベットを選んで、ラウンドを始めましょう"; document.querySelector(".table-card").classList.remove("is-win"); render(); }

document.querySelector("#betTargets").addEventListener("click", event => { const button = event.target.closest(".target-button"); if (!button || game.phase !== "betting") return; game.bets.target = button.dataset.target; document.querySelectorAll(".target-button").forEach(item => item.classList.toggle("is-selected", item === button)); document.querySelector("#dealButton small").textContent = "チップ額を選択してください"; render(); });
document.querySelector("#sideBets").addEventListener("click", event => { const button = event.target.closest(".side-bet-button"); if (!button || game.phase !== "betting") return; const name = button.dataset.sidebet; game.bets.sideBets = game.bets.sideBets.includes(name) ? game.bets.sideBets.filter(item => item !== name) : [...game.bets.sideBets, name]; button.classList.toggle("is-selected", game.bets.sideBets.includes(name)); render(); });
document.querySelector(".chip-row").addEventListener("click", event => { const button = event.target.closest("[data-amount]"); if (button && game.phase === "betting") { game.bets.amount += Number(button.dataset.amount); document.querySelector("#betValue").textContent = formatChips(game.bets.amount); document.querySelector("#dealButton small").textContent = "タップしてカードを配る"; render(); } if (event.target.closest("#clearBet") && game.phase === "betting") { game.bets.amount = 0; game.bets.sideBets = []; document.querySelector("#betValue").textContent = "0"; document.querySelectorAll(".side-bet-button").forEach(item => item.classList.remove("is-selected")); render(); } });
document.querySelector("#dealButton").addEventListener("click", startGame); document.querySelector("#revealAllButton").addEventListener("click", revealAll); document.querySelector("#newRoundButton").addEventListener("click", resetForNewRound);
document.querySelectorAll(".reveal-side-button").forEach(button => button.addEventListener("click", () => revealSide(button.dataset.owner))); document.querySelectorAll(".reveal-all-side-button").forEach(button => button.addEventListener("click", () => revealSide(button.dataset.owner))); document.querySelectorAll(".squeeze-side-button").forEach(button => button.addEventListener("click", event => openSqueezeView(getHiddenCards(button.dataset.owner)[0], button.dataset.direction, event.currentTarget)));
document.querySelector(".hands").addEventListener("click", event => { const cardElement = event.target.closest(".reveal-card"); if (!cardElement || suppressClick) { suppressClick = false; return; } openSqueezeView(findCard(cardElement.dataset.cardId), null, cardElement); });
document.querySelector(".hands").addEventListener("click", event => { const cardElement = event.target.closest(".reveal-card"); if (!cardElement) return; restoreSqueezeDirection(findCard(cardElement.dataset.cardId)); }, true);
document.querySelector("#squeezeModalCard").addEventListener("pointerdown", event => { if (!squeezeView.isSqueezeViewOpen || !["ready", "squeezing"].includes(squeezeView.squeezeViewPhase) || pointerSession || event.isPrimary === false) return; const card = findCard(squeezeView.activeSqueezeCardId); if (!card || card.revealState === "revealed") return; const element = event.currentTarget; const rect = element.getBoundingClientRect(); const localX = Math.max(0, Math.min(rect.width, event.clientX - rect.left)); const localY = Math.max(0, Math.min(rect.height, event.clientY - rect.top)); const direction = card.activeDirection; if (direction ? isValidSqueezeStart(direction, localX, localY, rect.width, rect.height) === false : !(localX <= rect.width * .25 || localX >= rect.width * .75 || localY >= rect.height * .75)) return; const progress = direction ? card.revealRegions[direction] ?? 0 : 0; const boundary = direction ? { x: ["left", "top-left", "bottom-left"].includes(direction) ? progress / 100 : ["right", "top-right", "bottom-right"].includes(direction) ? 1 - progress / 100 : localX / rect.width, y: ["top", "top-left", "top-right"].includes(direction) ? progress / 100 : ["bottom", "bottom-left", "bottom-right"].includes(direction) ? 1 - progress / 100 : localY / rect.height } : { x: 0, y: 0 }; pointerSession = { card, element, pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, startLocalX: localX, startLocalY: localY, rectWidth: rect.width, rectHeight: rect.height, grabOffsetX: localX / rect.width - boundary.x, grabOffsetY: localY / rect.height - boundary.y, moved: false }; squeezeView.cardRect = rect; squeezeView.isPointerActive = true; squeezeView.activePointerId = event.pointerId; element.setPointerCapture(event.pointerId); element.classList.add("is-dragging"); event.preventDefault(); });
document.querySelector("#squeezeModalCard").addEventListener("pointermove", event => { if (!pointerSession || event.pointerId !== pointerSession.pointerId) return; const session = pointerSession; const rect = session.element.getBoundingClientRect(); squeezeView.cardRect = rect; const localX = Math.max(0, Math.min(rect.width, event.clientX - rect.left)); const localY = Math.max(0, Math.min(rect.height, event.clientY - rect.top)); const dx = localX - session.startLocalX * rect.width / session.rectWidth; const dy = localY - session.startLocalY * rect.height / session.rectHeight; if (!session.moved && Math.hypot(dx, dy) < 8) return; session.moved = true; suppressClick = true; if (!session.card.activeDirection) { session.card.activeDirection = detectSqueezeDirection({ startX: session.startLocalX * rect.width / session.rectWidth, startY: session.startLocalY * rect.height / session.rectHeight, dx, dy, width: rect.width, height: rect.height, mode: squeezeMode }); session.grabOffsetX = session.startLocalX / session.rectWidth - (["right", "top-right", "bottom-right"].includes(session.card.activeDirection) ? 1 : 0); session.grabOffsetY = session.startLocalY / session.rectHeight - (["bottom", "bottom-left", "bottom-right"].includes(session.card.activeDirection) ? 1 : 0); } const direction = session.card.activeDirection; const boundary = { x: localX / rect.width - session.grabOffsetX, y: localY / rect.height - session.grabOffsetY }; setSqueezeProgress(session.card, direction, progressFromBoundary(direction, boundary)); event.preventDefault(); });
function endPointer(event) { if (!pointerSession || (event?.pointerId != null && event.pointerId !== pointerSession.pointerId)) return; pointerSession.element.releasePointerCapture?.(pointerSession.pointerId); pointerSession.element.classList.remove("is-dragging"); pointerSession = null; squeezeView.isPointerActive = false; squeezeView.activePointerId = null; document.body.classList.remove("is-squeeze-active"); }
document.querySelector("#squeezeModalCard").addEventListener("pointerup", endPointer); document.querySelector("#squeezeModalCard").addEventListener("pointercancel", endPointer); document.querySelector("#squeezeModalCard").addEventListener("lostpointercapture", endPointer);
document.addEventListener("pointerup", endPointer); document.addEventListener("pointercancel", endPointer);
document.querySelector("#squeezeDirectionPicker").addEventListener("click", event => { const button = event.target.closest("[data-squeeze-direction]"); if (!button || !squeezeView.isSqueezeViewOpen || !["ready", "squeezing"].includes(squeezeView.squeezeViewPhase) || pointerSession) return; const card = findCard(squeezeView.activeSqueezeCardId); if (!card) return; card.activeDirection = button.dataset.squeezeDirection; card.squeezeDirection = card.activeDirection; syncSqueezeView(card); });
document.querySelector("#squeezeModes").addEventListener("click", event => { const button = event.target.closest("[data-squeeze-mode]"); if (!button) return; squeezeMode = button.dataset.squeezeMode; document.querySelectorAll("#squeezeModes button").forEach(item => item.classList.toggle("is-selected", item === button)); });
document.querySelector("#squeezeCloseButton").addEventListener("click", closeSqueezeView); document.querySelector("#squeezeOpenButton").addEventListener("click", completeSqueezeView); document.querySelector("[data-squeeze-close]").addEventListener("click", closeSqueezeView);
document.querySelector("#squeezeModal").addEventListener("keydown", event => { if (event.key === "Escape") { event.preventDefault(); closeSqueezeView(); return; } if (event.key !== "Tab") return; const focusable = [...document.querySelectorAll("#squeezeModal button, #squeezeModalCard")].filter(element => !element.disabled); const current = focusable.indexOf(document.activeElement); const next = focusable[(current + (event.shiftKey ? -1 : 1) + focusable.length) % focusable.length]; event.preventDefault(); next?.focus(); });
document.querySelector("#resetButton").addEventListener("click", () => { if (!confirm("チップと履歴をリセットしますか？")) return; state = { balance: STARTING_CHIPS, history: [] }; game = freshGame(); saveState(); document.querySelector("#betValue").textContent = "0"; document.querySelectorAll(".target-button, .side-bet-button").forEach(button => button.classList.remove("is-selected")); document.querySelector("#resultLabel").textContent = "BET TO DEAL"; document.querySelector("#resultDetails").hidden = true; document.querySelector("#resultDetails").innerHTML = ""; document.querySelector("#tableMessage").textContent = "ベットを選んで、ラウンドを始めましょう"; document.querySelector(".table-card").classList.remove("is-win"); render(); });
render();
